spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/informacoes?createDatabaseIfNotExist=true
    username: root
    password: 1234
    initialization-mode: always
    initialize: true
    continue-on-error: true
  Jackson:
    default-property-inclusion: non_null
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  error:
    include-stacktrace: NEVER
    include-binding-errors: NEVER
  port: 8083
